# Generated by Django 4.0.5 on 2022-06-25 06:19

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('Userid', models.TextField()),
                ('Amount', models.FloatField()),
                ('Remark', models.TextField()),
                ('Type', models.TextField()),
                ('Category', models.TextField()),
            ],
        ),
    ]
